apiVersion: v1
kind: Pod
metadata:
  name: REPLACE_NAME
spec:
  containers:
   - name: kubectl
     image: lachlanevenson/k8s-kubectl:v1.11.2-bash
     resources:
       requests:
         memory: "1Gi"
     command:
     - cat
     tty: true
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    command:
    - cat
    tty: true
    volumeMounts:
      - name: maven-repo
        mountPath: "/root/.m2/repository"
  volumes:
    - name: maven-repo
      persistentVolumeClaim:
        claimName: efs
