apiVersion: v1
kind: Pod
metadata:
  name: REPLACE_NAME
spec:
  containers:
  - name: maven
    image: maven:3.3.9-jdk-8-alpine
    command:
    - cat
    tty: true
    volumeMounts:
      - name: maven-repo
        mountPath: "/root/.m2/repository"
  volumes:
    - name: maven-repo
      persistentVolumeClaim:
        claimName: REPLACE_NAME
